#!/usr/bin/env python3
"""
gen_runtime.py — generate the runtime bridge sources for the Simpsons port.

Post-lift step. Reconciles three sets of func_<addr> symbols:
  DECLARED  — declared in src/recomp/ppu_recomp.h   (lifter output)
  DEFINED   — have a body in src/recomp/ppu_recomp.cpp
  USED      — referenced (called) anywhere in ppu_recomp.cpp

Produces, into src/recomp/:
  * (patches ppu_recomp.h) — appends declarations for USED-but-not-DECLARED
    call targets so the big TU compiles.
  * func_table.cpp   — g_recompiled_funcs[] over DECLARED ∪ USED.
  * import_stubs.cpp — 256-entry import table {stub_addr, nid, lib, name}.
  * missing_stubs.cpp— empty bodies for every (DECLARED ∪ USED) − DEFINED so
    the link resolves.

Usage:  python tools/gen_runtime.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "src", "recomp", "ppu_recomp.h")
SOURCE = os.path.join(ROOT, "src", "recomp", "ppu_recomp.cpp")
IMPORTS = os.path.join(ROOT, "imports.json")
OUT_DIR = os.path.join(ROOT, "src", "recomp")

DECL_RE = re.compile(r"void (func_[0-9A-Fa-f]{8})\(ppu_context\* ctx\);")
DEF_RE = re.compile(r"^void (func_[0-9A-Fa-f]{8})\(ppu_context\* ctx\) \{")
TOK_RE = re.compile(r"func_[0-9A-Fa-f]{8}")
MARKER = "/* === gen_runtime.py: declarations for undeclared call targets === */"


def declared_funcs():
    return set(DECL_RE.findall(open(HEADER, "r", encoding="latin1").read()))


def scan_source():
    """One pass over the big TU: collect DEFINED and USED symbol sets."""
    defined, used = set(), set()
    with open(SOURCE, "r", encoding="latin1") as f:
        for line in f:
            m = DEF_RE.match(line)
            if m:
                defined.add(m.group(1))
            if "func_" in line:
                used.update(TOK_RE.findall(line))
    return defined, used


def patch_header(undeclared):
    """Append declarations for undeclared call targets (idempotent)."""
    text = open(HEADER, "r", encoding="latin1").read()
    if MARKER in text:
        text = text[: text.index(MARKER)].rstrip() + "\n"
    lines = [MARKER, '#ifdef __cplusplus', 'extern "C" {', "#endif"]
    lines += [f"void {fn}(ppu_context* ctx);" for fn in sorted(undeclared)]
    lines += ["#ifdef __cplusplus", "}", "#endif", ""]
    with open(HEADER, "w", encoding="latin1") as f:
        f.write(text + "\n" + "\n".join(lines))
    print(f"ppu_recomp.h: +{len(undeclared)} declarations for undeclared targets")


def gen_func_table(all_funcs):
    with open(os.path.join(OUT_DIR, "func_table.cpp"), "w", encoding="utf-8") as f:
        f.write('/* Auto-generated by tools/gen_runtime.py — do not edit. */\n')
        f.write('#include "ppu_recomp.h"\n#include <cstddef>\n#include <cstdint>\n\n')
        f.write('struct RecompiledFunc { uint32_t guest_addr; '
                'void (*host_func)(void* ctx); const char* name; };\n\n')
        f.write('extern "C" const RecompiledFunc g_recompiled_funcs[] = {\n')
        for fn in sorted(all_funcs):
            addr = int(fn[5:], 16)
            f.write(f'    {{ 0x{addr:08X}, (void(*)(void*))&{fn}, "{fn}" }},\n')
        f.write('};\n')
        f.write(f'extern "C" const size_t g_recompiled_func_count = {len(all_funcs)};\n')
    print(f"func_table.cpp: {len(all_funcs)} functions")


def gen_import_stubs():
    imp = json.load(open(IMPORTS))
    with open(os.path.join(OUT_DIR, "import_stubs.cpp"), "w", encoding="utf-8") as f:
        f.write('/* Auto-generated by tools/gen_runtime.py — do not edit. */\n')
        f.write('#include "ppu_recomp.h"\n#include <cstdint>\n#include <cstddef>\n\n')
        f.write('struct ImportEntry { uint32_t stub_addr; uint32_t nid; '
                'const char* lib; const char* name; };\n\n')
        f.write('extern "C" const ImportEntry g_imports[] = {\n')
        for x in imp:
            f.write(f'    {{ 0x{int(x["stub"],16):08X}, 0x{int(x["nid"],16):08X}, '
                    f'"{x["lib"]}", "{x.get("name","")}" }},\n')
        f.write('};\n')
        f.write(f'extern "C" const size_t g_import_count = {len(imp)};\n')
    print(f"import_stubs.cpp: {len(imp)} imports")


def gen_missing_stubs(missing):
    with open(os.path.join(OUT_DIR, "missing_stubs.cpp"), "w", encoding="utf-8") as f:
        f.write('/* Auto-generated by tools/gen_runtime.py — do not edit. */\n')
        f.write('#include "ppu_recomp.h"\n#include <cstdio>\n\n')
        for fn in sorted(missing):
            f.write(f'void {fn}(ppu_context* ctx) {{ (void)ctx; static int w=0; '
                    f'if(!w++) fprintf(stderr,"[stub] {fn} (unlifted)\\n"); }}\n')
    print(f"missing_stubs.cpp: {len(missing)} unlifted call targets")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    declared = declared_funcs()
    defined, used = scan_source()
    undeclared = used - declared
    all_funcs = declared | used
    missing = all_funcs - defined
    print(f"declared={len(declared)} defined={len(defined)} used={len(used)} "
          f"undeclared={len(undeclared)} stubs={len(missing)}")
    patch_header(undeclared)
    gen_func_table(all_funcs)
    gen_import_stubs()
    gen_missing_stubs(missing)
    print("done")
