#!/usr/bin/env python3
"""
gen_runtime.py — generate the runtime bridge sources for the Simpsons port.

Produces, into src/recomp/:
  * func_table.cpp   — g_recompiled_funcs[] mapping every lifted guest address
                       to its host func_<addr> (used for indirect bctrl dispatch).
  * import_stubs.cpp — the 256-entry import table {stub_addr, nid, lib, name}
                       plus simpsons_hle() dispatch entry point.

Inputs:
  src/recomp/ppu_recomp.h   — authoritative list of lifted func_<addr> symbols
  imports.json              — parsed from the EBOOT sys_proc_prx_param lib.stub

Usage:
  python tools/gen_runtime.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "src", "recomp", "ppu_recomp.h")
IMPORTS = os.path.join(ROOT, "imports.json")
OUT_DIR = os.path.join(ROOT, "src", "recomp")

FUNC_RE = re.compile(r"^void (func_[0-9A-Fa-f]{8})\(ppu_context\* ctx\);", re.M)


def gen_func_table():
    text = open(HEADER, "r", encoding="latin1").read()
    funcs = FUNC_RE.findall(text)
    funcs = sorted(set(funcs))
    out = os.path.join(OUT_DIR, "func_table.cpp")
    with open(out, "w", encoding="utf-8") as f:
        f.write('/* Auto-generated by tools/gen_runtime.py — do not edit. */\n')
        f.write('#include "ppu_recomp.h"\n#include <cstddef>\n#include <cstdint>\n\n')
        f.write('struct RecompiledFunc {\n'
                '    uint32_t guest_addr;\n'
                '    void   (*host_func)(void* ctx);\n'
                '    const char* name;\n};\n\n')
        f.write('extern "C" const RecompiledFunc g_recompiled_funcs[] = {\n')
        for fn in funcs:
            addr = int(fn[5:], 16)
            f.write(f'    {{ 0x{addr:08X}, (void(*)(void*))&{fn}, "{fn}" }},\n')
        f.write('};\n')
        f.write(f'extern "C" const size_t g_recompiled_func_count = {len(funcs)};\n')
    print(f"func_table.cpp: {len(funcs)} functions")
    return len(funcs)


def gen_import_stubs():
    imp = json.load(open(IMPORTS))
    out = os.path.join(OUT_DIR, "import_stubs.cpp")
    with open(out, "w", encoding="utf-8") as f:
        f.write('/* Auto-generated by tools/gen_runtime.py — do not edit. */\n')
        f.write('#include "ppu_recomp.h"\n#include <cstdint>\n#include <cstddef>\n\n')
        f.write('struct ImportEntry {\n'
                '    uint32_t stub_addr;\n'
                '    uint32_t nid;\n'
                '    const char* lib;\n'
                '    const char* name;\n};\n\n')
        f.write('extern "C" const ImportEntry g_imports[] = {\n')
        for x in imp:
            nm = x.get("name", "")
            f.write(f'    {{ 0x{int(x["stub"],16):08X}, 0x{int(x["nid"],16):08X}, '
                    f'"{x["lib"]}", "{nm}" }},\n')
        f.write('};\n')
        f.write(f'extern "C" const size_t g_import_count = {len(imp)};\n')
    # summary
    libs = {}
    for x in imp:
        libs[x["lib"]] = libs.get(x["lib"], 0) + 1
    print(f"import_stubs.cpp: {len(imp)} imports across {len(libs)} libraries")
    return len(imp)


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    gen_func_table()
    gen_import_stubs()
    print("done")
